#!/usr/bin/python

from findcomponent import FindComponent
import argparse

if __name__ == "__main__":

    parser = argparse.ArgumentParser()

    parser.add_argument('resistance', metavar='RESISTANCE', type=str, help='resistance (example: 10k)')
    parser.add_argument('--error', metavar='ERROR', type=float, help='maximum error from desired resistance in percent (default: 1)', default=1)
    parser.add_argument('--tolerance', metavar='TOLERANCE', type=float, help='maximum tolerance (default: 5)', default=5)
    parser.add_argument('--package', metavar='PACKAGE', type=str, help='package / case (default: 0603) (use ANY for any)', default='0603')

    args = parser.parse_args()
    
    comp = FindComponent()
    comp.resistor(args)


